name: ov
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py36_0
  - pip=19.3.1=py36_0
  - setuptools=44.0.0=py36_0
  - wheel=0.33.6=py36_0
  - pip:
    - chardet==3.0.4
    - decorator==4.4.1
    - defusedxml==0.5.0
    - idna==2.8
    - networkx==2.3
    - numpy==1.18.1
    - protobuf==3.6.1
    - pyyaml==5.3
    - requests==2.22.0
    - six==1.13.0
    - urllib3==1.25.7

